version: '3.1'
services:
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - ./data/mysql_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: $MARIADB_ROOT_PASSWORD

  adminer:
    image: adminer
    restart: always
    environment:
      ADMINER_DEFAULT_SERVER: mariadb
    ports:
      - 8080:8080