version: '3.1'
services:
  mariadb:
    image: mariadb
    restart: always
    volumes:
      - ./data:/var/lib/mysql
    ports:
      - 3306:3306
    environment:
      MYSQL_ROOT_PASSWORD: $MYSQL_ROOT_PASSWORD
  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080