services:
  rabbitmq:
    build: .
    container_name: rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=${USER}
      - RABBITMQ_DEFAULT_PASS=${PASS}
    ports:
      - 5672:5672
      - 15672:15672
      - 1883:1883
