name: .NET

on:
  push:
    branches: [ dotnet-mariadb ]
  pull_request:
    branches: [ dotnet-mariadb ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 5.0.x
    - name: Move directory
      run: ls -la
    - name: Restore dependencies
      run: dotnet restore
      working-directory: Integrator/
    - name: Build
      run: dotnet build -c release --no-restore
      working-directory: Integrator/
    - name: Test
      run: dotnet test --no-build --verbosity normal
      working-directory: Integrator/
